repos:

-   repo: https://github.com/psf/black
    rev: 23.9.1
    hooks:
    -   id: black
        types: [python]
        args: ["--config", "packages/light/pyproject.toml"]

-   repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
    -   id: isort
        name: isort (python)
        args: ["--settings-path", "packages/light/pyproject.toml"]