[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"


[project]
name = "panda-client-light"
dynamic = ["version"]
description = "Lightweight PanDA Client Package installed on PanDA server"
readme = "README.md"
license = "Apache-2.0"
requires-python = ">=2.7, !=3.0.*, !=3.1.*, !=3.2.*, !=3.3.*, !=3.4.*"
authors = [
    { name = "PanDA Team", email = "panda-support@cern.ch" },
]
classifiers = [
    "Programming Language :: Python",
    "Programming Language :: Python :: 2",
    "Programming Language :: Python :: 2.7",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.5",
    "Programming Language :: Python :: 3.6",
    "Programming Language :: Python :: 3.7",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
]


[project.urls]
Homepage = "https://panda-wms.readthedocs.io/en/latest/"


[tool.hatch.version]
path = "pandaclient/PandaToolsPkgInfo.py"
pattern = "release_version = \"(?P<version>[^\"]+)\""


[tool.hatch.build]
directory = "dist"


[tool.hatch.build.targets.wheel]
packages = ["pandaclient"]


[tool.black]
line-length=160

[tool.autopep8]
# https://pypi.org/project/autopep8/#pyproject-toml
max_line_length = 160
ignore = ["E501", "W6"]
in-place = true
recursive = true
aggressive = 3

[tool.isort]
profile = "black"
