#!/bin/bash

"export" "LD_LIBRARY_PATH_ORIG=${LD_LIBRARY_PATH}"
"export" "LD_LIBRARY_PATH="
"export" "PYTHONPATH_ORIG=${PYTHONPATH}"
"export" "PYTHONPATH=${PANDA_PYTHONPATH}"
"export" "PYTHONHOME_ORIG=${PYTHONHOME}"
"unset" "PYTHONHOME"
"exec" "/usr/bin/python" "-u" "-Wignore" "$0" "$@"

import os
import sys

from pandatools import pcontainer_core

os.environ['PANDA_EXEC_STRING'] = os.path.basename(sys.argv[0])

optP = pcontainer_core.make_arg_parse()

options = optP.parse_args()

status, output = pcontainer_core.submit(options)
sys.exit(status)
