[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "panda-client"
dynamic = ["version"]
description = "PanDA Client Package"
readme = {"text" = "PanDA Client Package", "content-type" = "text/markdown"}
license = "Apache-2.0"
requires-python = ">=2.7, !=3.0.*, !=3.1.*, !=3.2.*, !=3.3.*, !=3.4.*"
authors = [
    { name = "PanDA Team", email = "atlas-adc-panda@cern.ch" },
]
classifiers = [
    "Programming Language :: Python",
    "Programming Language :: Python :: 2",
    "Programming Language :: Python :: 2.7",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.5",
    "Programming Language :: Python :: 3.6",
    "Programming Language :: Python :: 3.7",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
]

[project.optional-dependencies]
jupyter = [
    "jupyter-dash",
    "pandas",
]

[project.urls]
Homepage = "https://panda-wms.readthedocs.io/en/latest/"

[tool.hatch.version]
path = "../../pandaclient/PandaToolsPkgInfo.py"
pattern = "release_version = \"(?P<version>[^\"]+)\""

[tool.hatch.build]
directory = "../../dist"
sources = ["src"]

[tool.hatch.build.force-include]
"../.." = "src"

[tool.hatch.build.targets.wheel]
exclude = ["*.template"]
packages = ["pandaclient", "pandatools", "pandaserver", "taskbuffer"]

[tool.hatch.build.targets.wheel.shared-data]
"templates" = "etc/panda"
"scripts" = "bin"
"share" = "etc/panda/share"

[tool.hatch.build.targets.wheel.hooks.custom]
path = "../hatch_build.py"


[tool.hatch.build.targets.sdist]
exclude = [
    "/.github",
]
